version: "3.8"

services:
  backend:
    build: ./backend
    container_name: node-backend
    restart: always
    ports:
      - "5000:5000"

  nginx:
    build: ./nginx
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

